birthday_reminder/accounts/urls.py
from django.conf.urls import url
from django.contrib.auth import views as auth_views

from . import views

urlpatterns = [
    url(r"^signup/$", views.signup, name="signup"),
    url(r'^login/$', auth_views.login, name='login'),
    url(r'^logout/$', auth_views.logout, name='logout'),
]

birthday_reminder/birthday_reminder/urls.py
from django.conf.urls import url, include
from django.conf.urls import handler404, handler500
from django.contrib import admin
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

from . import settings, views

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$', views.home, name="home"),
    url(r'^accounts/', include('accounts.urls', namespace="accounts")),
    url(r'^birthdays/', include('birthdays.urls', namespace="birthdays")),
]

handler404 = 'accounts.views.page_not_found'
handler404 = 'birthdays.views.page_not_found'

urlpatterns += staticfiles_urlpatterns()

birthday_reminder/birthdays/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r"^(?P<pk>\d+)/edit/$", views.edit_birthday, name="edit"),
    url(r"^(?P<pk>\d+)/confirm/$", views.confirm_delete, name="confirm"),
    url(r"^(?P<pk>\d+)/delete/$", views.delete_birthday, name="delete"),
    url(r"^all/$", views.birthday_list, name="list"),
    url(r"^create/$", views.create_birthday, name="create"),
    # url(r"^(?P<pk>\d+)/delete/$", views.delete_birthday, name="delete"),
]

birthday_reminder/accounts/models.py
from django.contrib.auth.models import (
    AbstractBaseUser,
    BaseUserManager,
    PermissionsMixin
)
from django.db import models
from django.utils import timezone


class UserManager(BaseUserManager):
    def create_user(self, email, username, password=None):
        if not email:
            raise ValueError("Users must have an email address.")

        user = self.model(
            email=self.normalize_email(email),
            username=username
        )
        user.set_password(password)
        user.save()
        return user

    def create_superuser(self, email, username, password):
        user = self.create_user(
            email,
            username,
            password
        )
        user.is_staff = True
        user.is_superuser = True
        user.save()
        return user


class User(AbstractBaseUser, PermissionsMixin):
    email = models.EmailField(unique=True)
    username = models.CharField(max_length=40, unique=True)
    date_joined = models.DateTimeField(default=timezone.now)
    is_active = models.BooleanField(default=True)
    is_staff = models.BooleanField(default=False)


    objects = UserManager()

    USERNAME_FIELD = "email"
    REQUIRED_FIELDS = ["username"]

    def __str__(self):
        return self.username

    def get_short_name(self):
        return self.username

birthday_reminder/birthdays/models.py
from django.conf import settings
from django.db import models
import datetime


class Birthday(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL)
    name = models.CharField(max_length=100)
    date_of_birth = models.DateField(null=True, help_text="yyyy-mm-dd")

    @property
    def age(self):
        return int((datetime.datetime.now().date() - self.date_of_birth).days / 365.25 )

    def __str__(self):
        return self.name

birthday_reminder/accounts/forms.py
from django import forms
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import UserCreationForm

from . import models


class UserCreateForm(UserCreationForm):
    class Meta:
        fields = (
            "username",
            "email",
            "password1",
            "password2"
        )
        model = get_user_model()

    def __init__(self, *args, **kwargs):
        super(UserCreateForm, self).__init__(*args, **kwargs)
        self.fields["email"].label = "Email address"

birthday_reminder/birthdays/forms.py
from django import forms
from . import models

class BirthdayFrom(forms.ModelForm):
    class Meta:
        model = models.Birthday
        fields = [
            "name",
            "date_of_birth"
        ]

    date_of_birth = forms.DateField(
        widget=forms.DateInput(format='%Y-%m-%d'),
        input_formats=('%Y-%m-%d', ),
        help_text = "yyyy-mm-dd"
        )

birthday_reminder/accounts/views.py
from django.contrib.auth import login, authenticate
from django.shortcuts import get_object_or_404, render, redirect
from django.http import HttpResponseRedirect

from . import forms
from . import models


def signup(request):
    if request.method == "POST":
        form = forms.UserCreateForm(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data.get('username')
            raw_password = form.cleaned_data.get('password1')
            user = authenticate(username=username, password=raw_password)
            if user is not None:
                login(request, user)
        return redirect("home")
    else:
        form = forms.UserCreateForm()
    return render(request, 'accounts/sign_up.html', {'form': form})


def page_not_found(request):
    response = render(request, '404.html')
    response.status_code = 404
    return response

birthday_reminder/birthday_reminder/views.py
# from django.http import HttpResponse
from django.shortcuts import render

def home(request):
    return render(request, 'home.html')

birthday_reminder/birthdays/views.py
from django.contrib.auth.decorators import login_required
from django.core.exceptions import ObjectDoesNotExist
from django.core.urlresolvers import reverse
from django.shortcuts import get_object_or_404, render, redirect
from django.http import HttpResponseRedirect

from datetime import date

from . import models
from . import forms


@login_required
def birthday_list(request):
    """show birthdays list"""
    today = date.today()
    birthdays = models.Birthday.objects.all().order_by('date_of_birth')
    bday = birthdays.filter(date_of_birth__month=today.month, date_of_birth__day=today.day)

    return render(request, 'birthday/birthday_list.html', {'birthdays': birthdays, 'bday': bday })


@login_required
def create_birthday(request, pk=None):
    """create a new birthday"""
    form = forms.BirthdayFrom()

    if request.method == "POST":
        form = forms.BirthdayFrom(request.POST)

        if form.is_valid():
            birthday = form.save(commit=False)
            birthday.user = request.user
            birthday.save()
            return HttpResponseRedirect(reverse("birthdays:list"))
    return render(
        request,
        'birthday/birthday_form.html', {
        'form': form })


@login_required
def edit_birthday(request, pk):
    """update a birthday"""
    try:
        birthday = models.Birthday.objects.get(pk=pk, user=request.user)
    except ObjectDoesNotExist:
        birthday = None

    form = forms.BirthdayFrom(instance=birthday)

    if request.method == "POST":
        form = forms.BirthdayFrom(request.POST, instance=birthday)

        if form.is_valid():
            birthday = form.save(commit=False)
            birthday.user = request.user
            birthday.save()
            return HttpResponseRedirect(reverse("birthdays:list"))
    return  render(
        request,
        'birthday/birthday_form.html', {
        'form': form })


@login_required
def confirm_delete(request, pk):
    """Confirm deletion of a birthday"""
    try:
        birthday = models.Birthday.objects.get(pk=pk, user=request.user)
    except ObjectDoesNotExist:
        birthday = None
    return render(request, 'birthday/confirm.html', {'birthday': birthday})


@login_required
def delete_birthday(request, pk):
    """delete a birthday"""
    try:
        birthday = models.Birthday.objects.get(pk=pk, user=request.user)
    except ObjectDoesNotExist:
        birthday = None
    birthday.delete()
    return HttpResponseRedirect(reverse("birthdays:list"))

birthday_reminder/accounts/templates/accounts/sign_up.html
{% extends "layout.html" %}

{% block body_content %}
  <div class="container">
    <h2>Sign Up</h2>
      <div class="grid-60" style="width:60%;text-align:center;margin-right:20%;margin-left:20%">
        <form method="POST" enctype="multipart/form-data" style="text-align:left">
          {% csrf_token %}
          {{ form.as_p }}
          <div class="button" style="text-align:center">
            <button type="submit" class="submit-button">Sign Up</button>
          </div>
        </form>
      </div>
  </div>
{% endblock %}

birthday_reminder/birthdays/templates/birthday/birthday_form.html
{% extends "layout.html" %}

{% block body_content %}
<div class="container">
  <h2>Birthday</h2>
  <div class="grid-60" style="width:60%;text-align:center;margin-right:20%;margin-left:20%">
    <form method="POST" enctype="multipart/form-data" style="text-align:left">
      {% csrf_token %}
      {{ form.as_p }}
      <div class="button" style="text-align:center">
        <button type="submit" class="submit-button">Save</button>
      </div>
    </br>
      <div class="cancel-div" style="text-align:center">
        <a href="{% url "birthdays:list" %}" class="cancel">Cancel</a>
      <div>
    </form>
  </div>
</div>
{% endblock %}

birthday_reminder/birthdays/templates/birthday/birthday_list.html
{% extends "layout.html" %}
{% load static from staticfiles %}

{% block body_content %}
  <div id="message">
    {% for day in bday %}
      {% if day.user == request.user %}
      <h3>{{ day.name }} turned {{ day.age }} years old today! Happy birthday {{ day.name }} !<h3>
      {% endif %}
    {% endfor %}
  </div>
  <div class="container">
    <h2>All Birthdays</h2>

    <table id="birthdays">
      <tr>
        <th>Name</th>
        <th>Date of Birth</th>
      </tr>
      {% for birthday in birthdays %}
        {% if birthday.user == request.user %}
        <tr>
          <td>
            {{ birthday.name }}
          </td>
          <td>
            {{ birthday.date_of_birth }}

            <a href="{% url "birthdays:edit" pk=birthday.pk %}">
              <i class="fas fa-pen" style="margin-left:10px"></i>
            </a>
            <a href="{% url "birthdays:confirm" pk=birthday.pk %}">
              <i class="fas fa-trash-alt" style="margin-left:10px"></i>
            </a>

          </td>
        </tr>
        {% endif %}
      {% endfor %}
    </table>



    <!-- {% for birthday in birthdays %}
      <div class="inner-container" style="background-color:pink">
        <div class="list-container">
          <a href="{% url "birthdays:edit" pk=birthday.pk %}">
            <h4><b>{{ birthday.date_of_birth }}</b></h4>
            <p>{{ birthday.name }}</p>
          <a>
        </div>
      </div>
    {% endfor %} -->
  </div>

{% endblock %}

birthday_reminder/birthdays/templates/birthday/confirm.html
{% extends "layout.html" %}
{% load static from staticfiles %}

{% block body_content %}
  <div class="container">
    <h3>Are you sure you want to remove {{ birthday.name }}'s birthday ?</h3>
    <button class="submit-button"><a href="{% url 'birthdays:delete' pk=birthday.pk %}" style="color:black">Yes</a></button>
    <div class="cancel-div">
      <a href="{% url "birthdays:list" %}" class="cancel-button">Cancel</a>
    <div>
  </div>
{% endblock %}

birthday_reminder/templates/home.html
{% extends "layout.html" %}
{% load static from staticfiles %}

{% block body_content %}
  <div class="home">
    <h1>Birthday Reminder</h1>
    <h2><a href="{% url "birthdays:list" %}">See your friends birthday</a></h2>
  </div>
{% endblock %}

birthday_reminder/templates/layout.html
{% load static from staticfiles %}

<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <title>{% block title_tag %}Birthday Reminder{% endblock %}</title>
    <link rel="stylesheet" href="{% static 'css/layout.css' %}">

    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.6.3/css/all.css" integrity="sha384-UHRtZLI+pbxtHCWp1t77Bi1L4ZtiqrqD80Kn4Z8NTSRyMA2Fd33n5dQ8lWUE00s/" crossorigin="anonymous">


  <body>
    <nav>
      <h2></h2>
      <ul>
        {% if user.is_authenticated %}
          <li class="username">Hello {{ user.username }} !<li>
          <li><a href="{% url "birthdays:create" %}">Add New Birthday</a></li>
          <li><a href="{% url "accounts:logout" %}">Log Out</a></li>
        {% else %}
          <li><a href="{% url "accounts:signup" %}">Sign Up</a></li>
          <li><a href="{% url "accounts:login" %}">Sign In</a></li>
        {% endif %}
      </ul>
    </nav>
    {% block body_content %}{% endblock %}
  </body>
</html>